#!/usr/bin/env node
// Regenerates the "Upcoming deadlines" section of README.md between the
// DEADLINES:START / DEADLINES:END markers, from data/deadlines.json.
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'data', 'deadlines.json'), 'utf8'));
const readmePath = path.join(root, 'README.md');

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// A deadline's calendar day in its own timezone is the date part of the ISO
// string; comparing on that (AoE is the latest zone) keeps entries listed
// until they have passed everywhere.
const today = new Date();
const todayStr = new Date(today.getTime() - 12 * 3600 * 1000).toISOString().slice(0, 10); // AoE today

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').trim();
const fmtDay = (iso) => {
  const [y, m, d] = iso.slice(0, 10).split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
};

const rows = [];
for (const conf of data.conferences) {
  for (const dl of conf.deadlines || []) {
    const isDated = /^\d{4}-\d{2}-\d{2}/.test(String(dl.date));
    const day = isDated ? String(dl.date).slice(0, 10) : '9999-12-31'; // rolling → sort last
    if (isDated && day < todayStr) continue;
    rows.push({
      day,
      venue: `[${esc(conf.venue)} ${conf.year}](${conf.website})`,
      label: esc(dl.label) + (conf.status === 'estimated' ? ' *(estimated)*' : ''),
      date: isDated ? `${fmtDay(day)} (${esc(dl.tz || 'AoE')})` : 'Rolling — submit anytime',
      conf: esc(conf.dates) || '—',
      place: esc(conf.place) || '—',
      source: `[source](${(String(conf.source).split(/[;,\s]+/)[0]) || conf.website})`,
    });
  }
}
rows.sort((a, b) => a.day.localeCompare(b.day));

const lines = [
  '<!-- DEADLINES:START — auto-generated by tools/build-readme.js from data/deadlines.json; do not edit by hand -->',
  `## Upcoming deadlines`,
  '',
  `_${rows.length} upcoming deadlines across ${data.count} tracked venue-years · last updated **${data.lastUpdated}** · times are ${'Anywhere on Earth (AoE, UTC−12)'} unless noted._`,
  '',
  '| Venue | Deadline | Date | Conference | Where | Source |',
  '|---|---|---|---|---|---|',
  ...rows.map((r) => `| ${r.venue} | ${r.label} | ${r.date} | ${r.conf} | ${r.place} | ${r.source} |`),
  '<!-- DEADLINES:END -->',
];

const readme = fs.readFileSync(readmePath, 'utf8');
const out = readme.replace(
  /<!-- DEADLINES:START[\s\S]*?<!-- DEADLINES:END -->/,
  lines.join('\n')
);
fs.writeFileSync(readmePath, out);
console.log(`README.md: wrote ${rows.length} upcoming deadlines (dataset ${data.lastUpdated})`);
